config/routes.rb
Rails.application.routes.draw do
  mount LetsencryptHttpChallenge::Engine => "/" unless ENV['LE_HTTP_CHALLENGE_RESPONSE'].blank?

  devise_for :users, controllers: { registrations: "users/registrations" }


  scope '(:locale)', locale: /fr/ do
    root to: 'pages#home'

    resources :teams, only: [:index, :show, :new, :create] do
      resources :quotes, only: [:index, :update, :create, :destroy] do
        member do
          patch :like
        end
      end
    end

    resource :profile, only: [:show, :edit, :update]
    resources :enrollments, only: [:new, :create]
    get 'admin', to: 'pages#admin'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :team

end

app/models/quote.rb
class Quote < ApplicationRecord
  acts_as_votable
  belongs_to :team
  belongs_to :user

  validates :content, presence: true
  validates :author, presence: true

end

app/models/team.rb
class Team < ApplicationRecord
  has_many :quotes, dependent: :destroy
  has_many :enrollments

  validates :name, presence: true, uniqueness: true

  # record a secret id to invite members
  before_create do |team|
    digest = Digest::SHA2.new.to_s << Time.now.to_s
    team.invite_code = digest[0..63].split(//).sample(16).join
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter
  has_many :enrollments
  has_many :teams, through: :enrollment
  has_many :quotes

  validates :nickname, presence: :true, uniqueness: :true, on: :update

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = t('pundit.alert.not_authorized')
  #   redirect_to(root_path)
  # end

  def set_locale
    # Choosing an Implied Locale (http://guides.rubyonrails.org/i18n.html#choosing-an-implied-locale)
    I18n.locale = ( params[:locale] || extract_locale_from_accept_language_header ) || I18n.default_locale
  end

  def default_url_options
    {
      host: ENV['HOST'] || 'localhost:3000',
      locale: I18n.locale == I18n.default_locale ? nil : I18n.locale
    }
  end

  private

    def skip_pundit?
      devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
    end

    def extract_locale_from_accept_language_header
      request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first unless request.env['HTTP_ACCEPT_LANGUAGE'].nil?
    end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def new
    @enrollment = Enrollment.new
    authorize @enrollment
    @team = Team.new
  end

  def create
    @team = Team.find_by_invite_code(team_params[:invite_code])
    if @team
      authorize @team
      Enrollment.create(user: current_user, team: @team)
      flash[:notice] = t('.team_added', team: @team.name)
      redirect_to team_quotes_path(@team)
    else
      @team = Team.new
      authorize @team
      flash[:alert] = t('.invalid_code')
      render 'new'
    end
  end

  private

    def team_params
      params.require(:team).permit(:invite_code)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    redirect_to teams_path if current_user
  end

  def admin
    if current_user && current_user.admin?
      @teams = Team.order(:name)
      @users = User.order(:created_at)
    else
      redirect_to root_path
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def edit
    session[:return_to] ||= request.referer
  end

  def update
    if @user.update(user_params)
      flash[:notice] = t('.profile_updated')
      if session[:return_to] == new_user_registration_url
        redirect_to root_path
      else
        redirect_to session.delete(:return_to)
      end

    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:nickname)
    end

    def set_user
      @user = current_user
      authorize @user
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:update, :destroy, :like]
  before_action :set_team, only: [:index, :create, :update, :like, :destroy]

  def index
    @quotes = policy_scope(Quote.where(team: @team))
    if Enrollment.where(user: current_user, team: @team).any?
      authorize @quotes
      @quote = Quote.new
      authorize @quote
      @members = Enrollment.where(team: @team)
    else
      redirect_to root_path
    end
  end

  def create
    @quote = Quote.new(quote_params)
    @quote.team = @team
    @quote.user = current_user
    authorize @quote
    if @quote.save
      redirect_to team_quotes_path(@team)
    else
      redirect_to team_quotes_path(@team)
    end
  end

  def update
    @quote.update(quote_params)
    authorize @quote
    redirect_to team_quotes_path(@team)
  end

  def destroy
    @quote.destroy
    authorize @quote
    flash[:notice] = t('.quote_deleted')
    redirect_to team_quotes_path(@team)
  end

  def like
    if Enrollment.where(user: current_user, team: @team).any?
      authorize @quote
      if current_user.voted_for? @quote
        current_user.unvote_for @quote
      else
        current_user.up_votes @quote
      end

      respond_to do |format|
        format.html { redirect_to team_quotes_path(@team) }
        format.js
      end
    else
      redirect_to root_path
    end
  end

  private

    def set_team
      @team = Team.find(params[:team_id])
    end

    def set_quote
      @quote = Quote.find(params[:id])
    end

    def quote_params
      params.require(:quote).permit(:content, :author)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show]

  def index
    @teams = policy_scope(Team)
    authorize @teams
  end

  def show
  end

  def new
    @team = Team.new
    authorize @team
  end

  def create
    @team = Team.new(team_params)
    authorize @team
    if @team.save
      Enrollment.create(user: current_user, team: @team)
      flash[:notice] = t('.team_created', team: @team.name)
      redirect_to team_quotes_path(@team)
    else
      render 'new'
    end
  end

  private
    def set_team
      @team = Team.find(params[:id])
      authorize @team
    end

    def team_params
      params.require(:team).permit(:name)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  protected

  def after_sign_up_path_for(resource)
    edit_profile_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/helpers/quote_helper.rb
module QuoteHelper
  def quote_like_css(user, quote)
    return "fa fa-2x fa-heart-o" if user.nil?
    user.liked?(quote) ? "fa fa-2x fa-heart" : "fa fa-2x fa-heart-o"
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
  def quote_like_css(user, quote)
    icon = "fa fa-heart"
    return "#{icon}-o" if user.nil?
    user.liked?(quote) ? icon : "#{icon}-o"
  end

  def quote_owner(user, quote)
    if quote.user == user
      t('.by_you')
    elsif quote.user.nickname.empty?
      t('.by_user', user: 'anonym')
    else
      t('.by_user', user: quote.user.nickname.capitalize)
    end
  end
end

app/views/enrollments/new.html.slim
.container
  .row
    .col-xs-12.col-sm-8.col-md-6.col-sm-offset-2.col-md-offset-3
      .panel.panel-success
        .panel-heading = t('.join_team')
        .panel-body
          = form_tag enrollments_path, method: :post do
            .form-group
              = label_tag "team[invite_code]", t('.invite_code')
              = text_field_tag "team[invite_code]", "", class: 'form-control'
            = button_tag t('.enroll').html_safe, class: 'btn btn-success',
                                data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> #{t('.joining')}" }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title><%= meta_title %></title>
    <%= render 'shared/metatags' %>
    <%= favicon_link_tag 'favicon.png' %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/admin.html.slim
h1 = "#{@teams.count} teams"

.list-group
  - @teams.each do |team|
    li.list-group-item.flexbox.flexbox-between
      div
        = link_to team.name.capitalize, team_quotes_path(team)
        | &nbsp;(
        = t('users.members', count: team.enrollments.count)
        | )
      .label.label-info
        = t('quotes.quotes', count: team.quotes.count)

h1 = "#{@users.count} users"

.list-group
  - @users.each do |user|
    li.list-group-item.flexbox.flexbox-between
      div.flexbox.flexbox-between
        div
          - if user.admin
            .label.label-danger Admin
            | &nbsp;
          - if user.nickname
             = user.nickname.capitalize
          - else
             anonymous
        div
          | &nbsp;
          = "<#{user.email}>"

      .flexbox.flexbox-between
        div
          = pluralize(Quote.where(user: user).count, 'quote')
        div &nbsp; | &nbsp;
        div
          = pluralize(user.find_voted_items.count, 'like')
        div &nbsp; | &nbsp;
        div
          = "#{distance_of_time_in_words(Time.now, user.created_at)} ago"

app/views/pages/home.html.slim
.row
  .col-xs-12.col-sm-8.col-md-6.col-sm-offset-2.col-md-offset-3
    .panel.panel-default
      .panel-body
        h1
          | Quoteam
          br
          small = t('.catch_phrase')
        = link_to t('devise.shared.links.sign_up'), new_user_registration_path, class: 'btn btn-primary btn-block'
        
  .col-xs-12
    = image_tag 'quoteam_meta.png', class: 'img-responsive center-block'

app/views/profiles/edit.html.slim
.container
  .row
    .col-xs-12.col-sm-8.col-md-6.col-sm-offset-2.col-md-offset-3
      .panel.panel-success
        .panel-heading = t('.your_profile')
        .panel-body
          = simple_form_for @user, url: profile_path do |f|
            = f.error_notification
            
            = f.input :nickname
            = f.button :button, t('.update').html_safe, class: 'btn btn-warning', data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> #{t('.saving')}" }

app/views/quotes/_action_panel.html.slim
.quote-action-panel
  .flexbox.flexbox-between
    div
      - if policy(quote).destroy?
        = link_to team_quote_path(team, quote), method: :delete, class: 'btn btn-xs btn-warning' do
          i.fa.fa-trash
        | &nbsp;
      span.quote-action-panel-text
        = t('.time_ago', time: distance_of_time_in_words(Time.now, quote.created_at))
        | &nbsp;

      = quote_owner(current_user, quote)
      
      - if policy(quote).update?
        | &nbsp; (
        span.btn-link role="button" data-toggle="modal" data-target="#edit-quote-#{quote.id}"
          = t('.edit')
        | )
        
    div id="likes-#{quote.id}"
      em.likes = quote.get_likes.size
      '&nbsp;
      - if policy(quote).like?
        = link_to like_team_quote_path(team, quote), method: :patch, remote: true, class: 'text-red' do
          i class=quote_like_css(current_user,  quote)
      - else
        i class=quote_like_css(nil,  quote)

  = render 'quotes/edit_form', quote: quote

app/views/quotes/_create_form.html.slim
= simple_form_for [@team, quote] do |f|
  = f.input :content
  = f.input :author 
  = f.button :submit, class: 'btn btn-success'

app/views/quotes/_edit_form.html.slim
.modal.fade id="edit-quote-#{quote.id}" tabindex="-1" role="dialog"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4.modal-title = t('.edit')
      
      .modal-body
        = simple_form_for [@team, quote] do |f|
          = f.input :content
          = f.input :author 
          = f.button :button, t('.update'), class: 'btn btn-warning',
                              data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> #{t('.saving')}" }

app/views/quotes/_invite.html.slim
.modal.fade id="invite" tabindex="-1" role="dialog"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4.modal-title = t('quotes.index.share')
      .modal-body
        = text_field_tag "", team.invite_code, autofocus: true, class: "h4"

app/views/quotes/_new_form.html.slim
.modal.fade id="new-quote" tabindex="-1" role="dialog"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4.modal-title = t('.new')
      .modal-body
        = simple_form_for [@team, quote] do |f|
          = f.input :content
          = f.input :author 
          = f.button :button, t('.create').html_safe, class: 'btn btn-success',
                              data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> #{t('.saving')}" }

app/views/quotes/_quote.html.slim
.quote
  .h4.quote-content
    i.fa.fa-quote-left
    | &nbsp;
    = quote.content
  .quote-author = "— #{quote.author}"
  = render 'quotes/action_panel', quote: quote, team: team

app/views/quotes/index.html.slim
h1
  = @team.name
  button.btn.btn-primary.visible-xs.visible-sm role="button" data-toggle="modal" data-target="#invite"
    i.fa.fa-share-alt.fa-lg
  
  = render 'quotes/invite', team: @team

.panel.panel-info.visible-md.visible-lg
  .panel-body
    p = t('.share')
    = text_field_tag "", @team.invite_code

- if policy(@quote).create?
  button.btn.btn-primary.visible-md.visible-lg role="button" data-toggle="modal" data-target="#new-quote"
    i.fa.fa-plus
    | &nbsp;
    = t('.new')
  button.btn.btn-lg.btn-primary.visible-xs.visible-sm.mobile-fixed role="button" data-toggle="modal" data-target="#new-quote"
    i.fa.fa-plus.fa-lg
  = render 'quotes/new_form', quote: @quote

  hr

.container
  .row
    .col-xs-12.col-sm-8.col-md-6.col-sm-offset-2.col-md-offset-3
      - @quotes.each do |quote|
        = render 'quotes/quote', quote: quote, team: @team

app/views/quotes/like.js.erb
// Remove the border from selected link
$('#likes-<%= @quote.id %> > a').blur();

// Update liked number
$('#likes-<%= @quote.id %> > .likes').text(<%= @quote.get_likes.size %>);

// Toggle heart color
$('#likes-<%= @quote.id %> > a > i.fa').toggleClass('fa-heart');
$('#likes-<%= @quote.id %> > a > i.fa').toggleClass('fa-heart-o');

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.slim
footer
  .flexbox.flexbox-around.flex-wrap
    a.text-white.btn.btn-link data-toggle="modal" data-target="#about"
      = t('footer.about.title')

    .text-light
      = link_to "https://github.com/guillaumecabanel/quoteam", class: "text-white", target: "_blank" do
        span.visible-xs.visible-sm
          = t('footer.contribute_at')
          | &nbsp; &nbsp;
          i.fa.fa-github
          
        span.visible-md.visible-lg
          = t('footer.contribute_at')
          | &nbsp; &nbsp;
          i.fa.fa-github
          | /guillaumecabanel/quoteam
        
    
  = render 'shared/modal_about'
  

app/views/shared/_metatags.html.erb
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= image_url(meta_image) %>" />
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META['twitter_account'] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META['twitter_account'] %>">
<meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

<!-- Google+ Schema.org markup -->
<meta itemprop="name" content="<%= meta_title %>">
<meta itemprop="description" content="<%= meta_description %>">
<meta itemprop="image" content="<%= image_url(meta_image) %>">

app/views/shared/_modal_about.html.slim
.modal.fade#about tabindex="-1" role="dialog"
  .modal-dialog role="document"
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
        h4.modal-title = t('footer.about.title')
      
      .modal-body
        p = t('footer.about.description')
        hr
        = link_to "Vector image Designed by Freepik", "http://www.freepik.com/free-vector/chat-elements_1010187.htm", target: "_blank"
        br
        = link_to "https://github.com/guillaumecabanel/quoteam/blob/master/MIT-LICENSE", target: "_blank" do
          = t('footer.about.license')
        br
        p Favicon: message quote by Thomas Helbig from the Noun Project
      
      .modal-footer
        button.btn.btn-default type="button" data-dismiss="modal" Close

app/views/shared/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    = link_to 'QuoTeam', root_path, class: 'navbar-brand visible-sm visible-md visible-lg'

    ul.nav.navbar-nav.navbar-right.visible-md.visible-lg
      = render 'shared/navbar_settings'
      
    ul.nav.navbar-nav.navbar-right.visible-xs.visible-sm
      li
        a.dropdown-toggle data-toggle="dropdown" role="button"
          i.fa.fa-lg.fa-bars
        ul.dropdown-menu
          li.visible-xs = link_to root_path do
            i.fa.fa-home.fa-lg
          = render 'shared/navbar_settings'
        

app/views/shared/_navbar_settings.html.slim
- if current_user
  - if  current_user.nickname.empty?
      li.btn-warning = link_to t('profiles.choose_nickname'), edit_profile_path
  - else
      li = link_to current_user.nickname.capitalize, edit_profile_path
  
  li = link_to t('devise.sign_out'), destroy_user_session_path, method: 'delete'
- else
  li = link_to t('devise.shared.links.sign_up'), new_user_registration_path
  li = link_to t('devise.shared.links.sign_in'), new_user_session_path